name: "Build Modern Standby"
on:
  push:
    branches: [master]

env:
  PROJECT_PATH: "ModernStandbyFix/ModernStandbyFix.csproj"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ModernStandbyFix
          path: .\publish